insert into navigazione.AccountSocial 
values 
    ('Instagram','solemarIT','solemar'),
    ('YouTube','solemarYT','solemar'),
    ('tiktok','solemarIT','solemar'),
    ('Facebook','SolemarIT','solemar'),
    ('Instagram','marittimaIT','marittima'),
    ('TikTok','marittimaIT','marittima'),
    ('YouTube','marittimaChannel','marittima'),
    ('Instagram','medexpress','medexpress'),
    ('TikTok','MedexpressCompagnia','medexpress'),
    ('Facebook','compagniaMEDEXPRESS','medexpress'),
    ('Instagram','nemo.compagnia','nemo'),
    ('TikTok','nemoCompagnia','nemo'),
    ('YouTube','nemoCompagniaChannel','nemo'),
    ('Intagram','c_acqueblu','acqueblu'),
    ('TikTok','acqueBlu','acqueblu'),
    ('facebook','acqueBlueOfficialPage','acqueblu'),
    ('Instagram','CaremarOfficial','caremar'),
    ('facebook','CaremarOfficialPage','caremar'),
    ('YouTube','CaremarChannel','caremar'),
    ('Instagram','Medmar_Group','medmar'),
    ('TikTok','MedmarOfficial','medmar'),
    ('facebook ','MedmarGroupPage','medmar');
