insert into navigazione.cliente 
values 
    ('francisco','pw','Francesco','Rossetti'),
    ('redellefeste69','capodanno24','Natale','Pasquale'),
    ('ellocobielsa91','cavese91','Edinson','Esposito'),
    ('lapala90','Giobbe34','Ugo','Lapala'),
    ('miralanguleto','padelnuestro','Franco','Stupackuz'),
    ('robistick85','centurione','Roberto','Sticchi Fiusi'),
    ('lovefoligno','osolemio','Massimo','Bagnato'),
    ('yoursong1','lennoncannon','Elton','John'),
    ('mrjones63','lionheart','Hugh','Jones'),
    ('tammarogol','jessica09','Pasquale','Tammaro'),
    ('pisacaneant71','pluto10','Antonio','Pisacane'),
    ('renasone','vivaverdi','Ferdinando','Ubaldo'),
    ('monterrey89','nuevapassword.','Juan Pablo','Montoya'),
    ('picodellamirandola60','ulissemio12','Massimo','Ciarrapico'),
    ('ladybug33','gattonero','Denise','De Filippo'),
    ('lafrasne99','fiocchidineve','Emanuela','Frasnedi'),
    ('robchip','ftalatok','Roberta','Cipollo'),
    ('velleira03','narcisobianco','Talia','Velleira'),
    ('derkanzler54',' Schokoladenkekse','Angela','Merkel');
