insert into navigazione.natante 
values 
    ('Benito Buono','medmar',800,90,'traghetto'::navigazione.tiponatante),
    ('Rosa D''Abundo','medmar',650,50,'traghetto'::navigazione.tiponatante),
    ('Tourist Ferry Boat III','medmar',293,30,'traghetto'::navigazione.tiponatante),
    ('Saetta','acqueblu',500,0,'motonave'::navigazione.tiponatante),
    ('Cricchetto','acqueblu',550,115,'traghetto'::navigazione.tiponatante),
    ('Pupone','acqueblu',640,75,'traghetto'::navigazione.tiponatante),
    ('Zio Paperone','acqueblu',400,0,'aliscafo'::navigazione.tiponatante),
    ('Apollo23','solemar',100,50,'traghetto'::navigazione.tiponatante),
    ('Dorata','solemar',400,0,'motonave'::navigazione.tiponatante),
    ('Poseidone','solemar',250,0,'aliscafo'::navigazione.tiponatante),
    ('Esdrongo','marittima',115,65,'traghetto'::navigazione.tiponatante),
    ('Mietitore','marittima',235,0,'aliscafo'::navigazione.tiponatante),
    ('Dorita','marittima',980,0,'motonave'::navigazione.tiponatante),
    ('Reina','medexpress',100,35,'traghetto'::navigazione.tiponatante),
    ('Princess','medexpress',650,0,'motonave'::navigazione.tiponatante),
    ('King','medexpress',240,0,'aliscafo'::navigazione.tiponatante),
    ('Navigante','nemo',145,70,'traghetto'::navigazione.tiponatante),
    ('Chiaretta','nemo',600,0,'motonave'::navigazione.tiponatante),
    ('Vamonos','caremar',150,55,'traghetto'::navigazione.tiponatante),
    ('Cacciatore','caremar',125,70,'traghetto'::navigazione.tiponatante),
    ('Miuzzola','caremar',860,0,'motonave'::navigazione.tiponatante);
