insert into navigazione.Veicolo 
values 
    ('NA052DE','francisco','motociclo'::navigazione.tipoveicolo),
    ('GG104EZ','redellefeste69','motociclo'::navigazione.tipoveicolo),
    ('AS265DF','derkanzler54','automobile'::navigazione.tipoveicolo),
    ('DF386GT','derkanzler54','motociclo'::navigazione.tipoveicolo),
    ('DF763GY','derkanzler54','motociclo'::navigazione.tipoveicolo),
    ('GH639FF','velleira03','mezzo pesante'::navigazione.tipoveicolo),
    ('DB220EZ','velleira03','altro'::navigazione.tipoveicolo),
    ('GG110EZ','robchip','automobile'::navigazione.tipoveicolo),
    ('RT685IJ','lafrasne99','motociclo'::navigazione.tipoveicolo),
    ('GH095KJ','lafrasne99','automobile'::navigazione.tipoveicolo),
    ('FT765YH','ladybug33','automobile'::navigazione.tipoveicolo),
    ('HJ768VB','tammarogol','motociclo'::navigazione.tipoveicolo),
    ('DC546GJ','pisacaneant71','automobile'::navigazione.tipoveicolo),
    ('GF657JJ','lovefoligno','altro'::navigazione.tipoveicolo),
    ('CE857ED','lapala90','mezzo pesante'::navigazione.tipoveicolo),
    ('BA025QW','lapala90','motociclo'::navigazione.tipoveicolo),
    ('CE234QW','miralanguleto','motociclo'::navigazione.tipoveicolo),
    ('QA324LP','robistick85','altro'::navigazione.tipoveicolo),
    ('AB589PO','robistick85','automobile'::navigazione.tipoveicolo),
    ('AD780FG','mrjones63','mezzo pesante'::navigazione.tipoveicolo),
    ('YI090QP','mrjones63','automobile'::navigazione.tipoveicolo),
    ('CR842PL','mrjones63','motociclo'::navigazione.tipoveicolo),
    ('AB408RH','pisacaneant71','motociclo'::navigazione.tipoveicolo),
    ('YD999WT','pisacaneant71','altro'::navigazione.tipoveicolo),
    ('TR013WS','pisacaneant71','mezzo pesante'::navigazione.tipoveicolo),
    ('CB900MN','renasone','motociclo'::navigazione.tipoveicolo),
    ('BR556TY','renasone','automobile'::navigazione.tipoveicolo),
    ('PI765YT','picodellamirandola60','mezzo pesante'::navigazione.tipoveicolo),
    ('VR708UT','picodellamirandola60','motociclo'::navigazione.tipoveicolo);

